export const siteConfig = {
  title: "Side One — A Private Vinyl Catalog",
  applicationName: "Side One",
  description:
    "Browse complete track lists, inspect each pressing, and cue locally owned music on a tactile 3D turntable.",
  wordmark: "SIDE ONE",
  collectionName: "A PRIVATE VINYL CATALOG",
  editionEyebrow: "SELECTED PRESSING",
  coverImprint: "SIDE ONE",
  coverTagline: "PLAY IT AGAIN",
  spineMark: "S1",
  playLabel: "Play",
  pauseLabel: "Pause",
  stopLabel: "Stop",
  returnLabel: "Back to collection",
  externalLinkLabel: "View official release",
  mintPlaygroundLabel: "Mint Playground",
  mintPlaygroundUrl: "https://github.com/mintdotgg/mint-playground",
  socialImageAlt:
    "Side One, a private vinyl catalog represented by a black record emerging from a minimal white sleeve.",
  independentNote:
    "Official links for every record. Audio remains local.",
  theme: {
    paper: "#f3f0e9",
    paperDeep: "#e7e1d7",
    paperLight: "#faf8f4",
    ink: "#24211e",
    inkSoft: "#746d65",
    accent: "#7c5b3b",
    tan: "#a67c52",
    line: "#d8d0c5",
    structure: "#4a423b",
    softHover: "#eee8df",
    night: "#24211e",
    brass: "#a67c52",
  },
} as const;
